export const APP_NAME = '管理系统'
export const API_VERSION = 'v1'
export const API_BASE_URL = '/api'
export const TOKEN_KEY = 'access_token'
export const REFRESH_TOKEN_KEY = 'refresh_token'
export const USER_INFO_KEY = 'user_info'
export const MAX_LOGIN_ATTEMPTS = 5
export const SESSION_TIMEOUT = 30 * 60 * 1000
export const DEFAULT_PAGE_SIZE = 20
export const PAGE_SIZES = [10, 20, 50, 100]
